steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/model-union-469912-h2/izza-medical-ai', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/model-union-469912-h2/izza-medical-ai']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'izza-medical-ai'
      - '--image'
      - 'gcr.io/model-union-469912-h2/izza-medical-ai'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
images:
  - 'gcr.io/model-union-469912-h2/izza-medical-ai'
timeout: '1200s'
